stages:
  train-decoder:
    desc: Training and on-target predictions of EEG decoder.
    cmd: julia -t auto --project=. -- scripts/julia/train_decode.jl
    deps:
    - scripts/julia/setup_decode_params.jl
    - data/processed/analyses/decode-data
    - data/processed/eeg
    outs:
    - data/processed/analyses/decode:
        persist: true
  decode-timeline:
    desc: Evaluating decoder accuracy across trial timeline.
    cmd: julia -t auto --project=. -- scripts/julia/process_decode_timeline.jl
    deps:
    - scripts/julia/setup_decode_params.jl
    - data/processed/analyses/decode-data
    - data/processed/analyses/decode
    - data/processed/eeg
    outs:
    - data/processed/analyses/decode-timeline:
        persist: true
  load-decoder-data:
    desc: Organize and downsample EEG data for decoding.
    cmd: julia -t auto --project==. -- scripts/julia/load_decode_data.jl
    deps:
    - data/processed/eeg
    outs:
    - data/processed/analyses/decode-data:
        persist: true
  decode-timeline-source:
    desc: Evaluating decoder accuracy across trial timeline.
    cmd: julia -f auto --project=. -- scripts/julia/process_decode_source_timeline.jl
    deps:
    - data/processed/analyses/decode
    - data/processed/analyses/decode-varlag
    - data/processed/eeg
    outs:
    - data/processed/analyses/decode-timeline-source:
        persist: true
  decode-timeline-switch:
    desc: Evaluating decoder accuracy across trial timeline.
    cmd: julia -t auto --project=. -- scripts/julia/process_decode_source_by_switch_timeline.jl
    deps:
    - scripts/julia/setup_decode_params.jl
    - data/processed/analyses/decode-data
    - data/processed/analyses/decode-varlag
    - data/processed/analyses/decode
    - data/processed/eeg
    outs:
    - data/processed/analyses/decode-timeline-switch:
        persist: true
  train-decoder-varlag:
    desc: Training and on-window predictions for varying time lag ranges.
    cmd: julia -f auto --project=. -- scripts/julia/train_decode_varlags.jl
    deps:
    - data/processed/analyses/decode-data
    - data/processed/eeg
    - scripts/julia/setup_decode_params.jl
    outs:
    - data/processed/analyses/decode-varlag:
        persist: true
  parse-mixture-channels:
    desc: Prepare different channels for pitch tracking by CREPE.
    cmd: julia -t auto --project=. -- scripts/julia/mix_component_channels.jl
    deps:
    - data/processed/stimuli/mixtures/testing/mixture_components
    outs:
    - data/processed/stimuli/mixtures/testing/mixture_component_channels:
        persist: true
  find-channel-pitches:
    desc: Use CREPE to find each sound source's pitch.
    cmd: julia -t auto --project=. -- scripts/julia/find_pitches.jl
    deps:
    - data/processed/stimuli/mixtures/testing/mixture_component_channels
    outs:
    - data/processed/stimuli/mixtures/testing/mixture_component_pitches:
        persist: true
